; =============================================================================
; PLATFORMIO CONFIGURATION FILE - MINGGU 10: FREERTOS DUAL-CORE & DEFERRED ISR
; Laboratorium Sistem Tertanam (Embedded Systems) - Teknik Elektro
; Target Hardware: ESP32-WROOM-32 / ESP32-S3 (30/38 Pin DevKit)
; =============================================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Kecepatan komunikasi Serial Monitor (Baud Rate)
monitor_speed = 115200

; Filter otomatis Serial Monitor untuk debugging dan dekode crash
monitor_filters = 
    esp32_exception_decoder
    time

; Mode build debug untuk mempermudah penelusuran crash backtrace jika terjadi kesalahan ISR
build_type = debug

; Kernel FreeRTOS Symmetric Multiprocessing (SMP) sudah terintegrasi native di ESP-IDF & Arduino ESP32.
