; =============================================================================
; PLATFORMIO CONFIGURATION FILE - MINGGU 05: SERIAL PROTOCOLS & LOGIC ANALYZER
; Laboratorium Sistem Tertanam (Embedded Systems) - Teknik Elektro
; Target Hardware: ESP32-WROOM-32 / ESP32-S3 (30/38 Pin DevKit)
; =============================================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Kecepatan komunikasi Serial Monitor (Baud Rate)
monitor_speed = 115200

; Filter otomatis Serial Monitor untuk debugging nyaman
monitor_filters = 
    esp32_exception_decoder
    time

; Mode build debug
build_type = debug

; Dependensi library (Pustaka Wire dan SPI sudah bawaan inti Arduino ESP32)
; Jika Anda menggunakan sensor fisik BME280 / OLED fisik, Anda dapat mengaktifkan:
; lib_deps = 
;     adafruit/Adafruit BME280 Library @ ^2.2.4
;     adafruit/Adafruit SSD1306 @ ^2.5.9
;     adafruit/Adafruit GFX Library @ ^1.11.9
