; =============================================================================
; PLATFORMIO CONFIGURATION FILE - MINGGU 06: INDUSTRIAL BUS (CAN & RS-485)
; Laboratorium Sistem Tertanam (Embedded Systems) - Teknik Elektro
; Target Hardware: ESP32-WROOM-32 / ESP32-S3 (30/38 Pin DevKit)
; =============================================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Kecepatan komunikasi Serial Monitor (Baud Rate)
monitor_speed = 115200

; Filter otomatis Serial Monitor untuk debugging
monitor_filters = 
    esp32_exception_decoder
    time

; Mode build debug
build_type = debug

; Catatan: Driver TWAI (CAN Bus 2.0B) dan HardwareSerial (RS-485) sudah 
; terintegrasi langsung di dalam inti ESP-IDF dan Arduino Core ESP32.
; Tidak diperlukan instalasi pustaka pihak ketiga eksternal untuk pengujian dasar!
