; =============================================================================
; PLATFORMIO CONFIGURATION FILE - MINGGU 04: PERSISTENT STORAGE (NVS & LITTLEFS)
; Platform: Espressif 32 (ESP32-WROOM-32 / ESP32-S3)
; Framework: Arduino Core
; =============================================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Kecepatan komunikasi Serial Monitor (sesuai Serial.begin(115200))
monitor_speed = 115200

; Filter otomatis Serial Monitor
monitor_filters = 
    esp32_exception_decoder
    time

; Mode debug untuk crash decoding
build_type = debug

; Gunakan tabel partisi kustom yang telah didefinisikan di partitions.csv
board_build.partitions = partitions.csv

; Tentukan filesystem yang digunakan adalah LittleFS (bukan SPIFFS lama)
board_build.filesystem = littlefs
