; PlatformIO Project Configuration File for Week 02 Lab
; Topik: Karakteristik Elektrikal Pin, Hardware Interrupt & Crash Debugging

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Filter monitor otomatis menerjemahkan Guru Meditation Crash Backtrace
; menjadi nomor baris dan nama fungsi pada file sumber C/C++
monitor_filters = 
    esp32_exception_decoder
    default

; Mode kompilasi debug untuk menghasilkan tabel simbol lengkap
build_type = debug
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -Wall
