; =============================================================================
; PLATFORMIO CONFIGURATION FILE - MINGGU 03: TRANSISTOR DRIVER, ADC1 & PWM
; Platform: Espressif 32 (ESP32-WROOM-32 / ESP32-S3)
; Framework: Arduino Core
; =============================================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Kecepatan komunikasi Serial Monitor (sesuai kode program Serial.begin(115200))
monitor_speed = 115200

; Filter otomatis Serial Monitor:
; - esp32_exception_decoder: menerjemahkan crash dump secara otomatis
; - time: menambahkan timestamp waktu pada setiap baris log serial
monitor_filters = 
    esp32_exception_decoder
    time

; Mode debug agar tabel simbol biner (.elf) menyertakan nama fungsi dan nomor baris
build_type = debug
