; PlatformIO Project Configuration File for Week 01 Lab
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Optimasi compiler untuk pembelajaran teknik elektro
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -Wall
